import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen w-full">
        <div className="bg"></div>
        <NavBar />
        <div className=' mt-20'>
          <section className='max-w-screen-lg mx-auto w-full flex justify-between'>
            <div className='block my-auto'>
              <span>
                <h1 className='text-white font-sans text-6xl font-bold'>Hi, <br/> I'm Laura</h1>
                <p className='text-2xl font-light mt-2'>A fullstack web developer.</p>
              </span>
              <button className='bg-one px-6 py-2 rounded-md mt-4'>
                Contact
              </button>
            </div>
            <div className="">
              <img src="/mock.jpg" width={500} />
            </div>
          </section>
          <section id="special" className='py-16 mt-56'>
           <div className='max-w-screen-lg mx-auto  flex justify-between'>
           <div className="pr-16">
              <img src="/mock.jpg" width={500} />
            </div>
            <span className='max-w-prose my-auto'>
                <h1 className='text-white font-sans text-3xl font-semibold text-right'>Sed ut perspiciatis unde omnis</h1>
                <p className='text-right font-light mt-2'>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem.</p>
              </span>
           </div>
          </section>
          <section className='max-w-screen-lg mx-auto'>
            <h1 className='text-white text-center text-4xl font-sans font-bold mt-32'>Skills</h1>
            <p className='text-center mx-auto font-light mt-2 max-w-prose'>Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem.</p>
            <div className='flex flex-wrap justify-center space-x-6 py-10'>
              <img src='/next.svg' width={150} />
              <img src='/next.svg' width={150} />
              <img src='/next.svg' width={150} />
              <img src='/next.svg' width={150} />
              <img src='/next.svg' width={150} />
              <img src='/next.svg' width={150} />
            </div>
          </section>
        </div>
        <Footer />
      </main>
    </>
  )
}
